In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

# 1. tensorflow v2.xx에서 v1 사용하기

In [2]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tensorflow v2 비활성화하고 v1활성화
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


## Tensorflow
- 테이터 흐름 그래프(tensor 객체의 흐름)을 사용하는 수치 계산 라이브러리
- 그래프는 node(연산)와 edge로 구성
- sess = tf.Session()을 이용해서 실행 환경
- sess.run()을 통해서 실행 결과를 확인

In [3]:
# 1단계 : tensor(상수 노드 하나) 정의 
node1 = tf.constant('Hello, Tensorflow')
# 2단계 : 세션(연상을 실행하는 환경) 생성
sess = tf.Session()
# 3단계 : 실제 실행 및 출력
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello, Tensorflow'
Hello, Tensorflow


In [6]:
# 간단한 연산 tensor 그래프
node1 = tf.constant(10, dtype=tf.float16)
node2 = tf.constant(20, dtype=tf.float16)
node3 = tf.add(node1, node2)
# 2.세션 생성
sess = tf.Session()
# 3. 세션 실행 & 결과
print(sess.run([node1, node2, node3]))

[10.0, 20.0, 30.0]


In [9]:
# 타입변경
import numpy as np
node1 = tf.constant(np.array([1,2,3]), dtype=tf.int16) 
node2 = tf.cast(node1, dtype=tf.float16)
sess = tf.Session()
print(sess.run([node1, node2]))

[array([1, 2, 3], dtype=int16), array([1., 2., 3.], dtype=float16)]


In [11]:
# 평균값 계산 : tf.reduce_mean()
data = np.array([1.,2.,3.,4.])
m = tf.reduce_mean(data)
sess = tf.Session()
print(sess.run(m))

2.5


In [12]:
# tf.random_normal([size]) : 평균이 0이고 표준편차가 1인 난수 size개 발생
w = tf.random_normal([3]) 
sess = tf.Session()
sess.run(w)

array([ 0.5000221 , -0.8175298 ,  0.59330034], dtype=float32)

In [13]:
#  변수 노드
w = tf.Variable(tf.random_normal([1]))
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 변수 초기화
sess.run(w)

array([-2.5918694], dtype=float32)

# 2. tensorflow v1을 이용한 회귀분석 구현
## 2.1 독립변수 x가 1개, 타겟(종속)변수 y가 1개

In [18]:
# tensor 그래프 정의
# 데이터 셋 확보
x = np.array([1,2,3])
y = np.array([2,3,4])
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse )
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 W, b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 곡선위 미분값이 0이 되는 방향
(경사하강법GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W, B 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b])
    if step%300==0:
        print("{}번째 cost:{}, W:{}, b:{}".format(step, cost_val, W_val, b_val))

0번째 cost:16.0811767578125, W:[-0.7216832], b:[1.1642232]
300번째 cost:0.02028021588921547, W:[0.8349989], b:[1.3750863]
600번째 cost:0.004785303957760334, W:[0.9198495], b:[1.1822007]
900번째 cost:0.0011291397968307137, W:[0.9610664], b:[1.0885054]
1200번째 cost:0.00026643063756637275, W:[0.98108786], b:[1.0429919]
1500번째 cost:6.286892312346026e-05, W:[0.9908132], b:[1.020884]
1800번째 cost:1.4833763998467475e-05, W:[0.9955375], b:[1.0101441]
2100번째 cost:3.4994016004930018e-06, W:[0.99783254], b:[1.004927]
2400번째 cost:8.257395620603347e-07, W:[0.9989472], b:[1.0023934]
2700번째 cost:1.9492193814585335e-07, W:[0.9994884], b:[1.0011629]
3000번째 cost:4.6198305625466674e-08, W:[0.9997508], b:[1.0005662]
3300번째 cost:1.1020413914764049e-08, W:[0.99987817], b:[1.0002763]
3600번째 cost:2.692383871405468e-09, W:[0.99993986], b:[1.0001366]
3900번째 cost:6.652101092186058e-10, W:[0.9999703], b:[1.0000682]
4200번째 cost:1.5189982605079422e-10, W:[0.99998575], b:[1.0000324]
4500번째 cost:8.733517381509515e-11, W:[0.999

In [21]:
# 최종적으로 나온 회귀식 H - W*x + b
W_, b_ = sess.run([W, b])

In [23]:
def predict(x):
    return W_[0] * x + b_[0]

In [24]:
predict(5)

5.999970257282257

## 2.2 predict을 위한 placeholder 이용
-  placeholder : 외부에서 데이터를 입력받을 수 있는 노드


In [27]:
x = tf.placeholder(dtype=tf.float32)
H = 1* x + 1
sess = tf.Session()
sess.run([x, H], feed_dict={x : np.array([1,2,3])})

[array([1., 2., 3.], dtype=float32), array([2., 3., 4.], dtype=float32)]

In [28]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,3])
y_data = np.array([2,3,4])
# placeholder 설정(x, y)
x= tf.placeholder(dtype=tf.float32)
y= tf.placeholder(dtype=tf.float32)


# weight와 bias
W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse )
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 W, b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 곡선위 미분값이 0이 되는 방향
(경사하강법GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W, B 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b],
                                        feed_dict={x:x_data,
                                                  y:y_data})
    if step%300==0:
        print("{}번째 cost:{}, W:{}, b:{}".format(step, cost_val, W_val, b_val))

0번째 cost:5.475037097930908, W:[0.23054776], b:[0.5556617]
300번째 cost:0.00026755747967399657, W:[1.018952], b:[0.9569171]
600번째 cost:6.31293878541328e-05, W:[1.0092059], b:[0.9790726]
900번째 cost:1.4897286746418104e-05, W:[1.004472], b:[0.9898341]
1200번째 cost:3.515732714731712e-06, W:[1.0021726], b:[0.99506146]
1500번째 cost:8.298858915622986e-07, W:[1.0010556], b:[0.9976006]
1800번째 cost:1.9625815639301436e-07, W:[1.0005134], b:[0.9988332]
2100번째 cost:4.657463748003465e-08, W:[1.0002505], b:[0.99943155]
2400번째 cost:1.1072965655500866e-08, W:[1.0001221], b:[0.99972266]
2700번째 cost:2.6803756991711225e-09, W:[1.0000601], b:[0.999864]
3000번째 cost:6.327098844849388e-10, W:[1.000029], b:[0.9999338]
3300번째 cost:1.6977234895687587e-10, W:[1.0000153], b:[0.9999658]
3600번째 cost:5.195962063386794e-11, W:[1.0000086], b:[0.9999813]
3900번째 cost:5.195962063386794e-11, W:[1.0000086], b:[0.9999813]
4200번째 cost:5.195962063386794e-11, W:[1.0000086], b:[0.9999813]
4500번째 cost:5.195962063386794e-11, W:[1.00000

In [29]:
# 예측하기
sess.run(H, feed_dict={x:7})

array([8.000041], dtype=float32)

## 2.3 scale이 다른 데이터들의 회구분석 구현 (scale 


In [33]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost (손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)
train = optimizer.minimize(cost)
# Session & 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:x_data, y:y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step+1, cost_val))

301/6000번째 cost:109.3749771118164
601/6000번째 cost:79.40104675292969
901/6000번째 cost:79.14396667480469
1201/6000번째 cost:79.14170837402344
1501/6000번째 cost:79.14160919189453
1801/6000번째 cost:79.14154052734375
2101/6000번째 cost:79.14144134521484
2401/6000번째 cost:79.14140319824219
2701/6000번째 cost:79.14129638671875
3001/6000번째 cost:79.14125061035156
3301/6000번째 cost:79.14119720458984
3601/6000번째 cost:79.14112854003906
3901/6000번째 cost:79.14106750488281
4201/6000번째 cost:79.14103698730469
4501/6000번째 cost:79.14096069335938
4801/6000번째 cost:79.1408920288086
5101/6000번째 cost:79.14086151123047
5401/6000번째 cost:79.14078521728516
5701/6000번째 cost:79.14076232910156
6001/6000번째 cost:79.14069366455078


## 2.4 scale이 다른 데이터들의 회귀분석 구현(조정 O)
### scale 조정방법 : 모든 데이터를 일정범위내로 조정
- normalization(정규화) : 모든 데이터를 0~1 사이로 조정
                        X - Xmin
    normalization = ─────────────────
                       Xmax - Xmin
       * 위의 식보다 라이브러리 추천(sklearn.preprocessing.MinMaxSxaler)
- standarization(표준화) : 데이터의 평균을 0, 표준편차를 1로 조정
                        X - Xmean
    standarization = ─────────────────
                       Xstd(표준편차)
       * 위의 식보다 라이브러리 추천(sklearn.preprocessing.StadardScaler)

In [38]:
# 라이러브 쓰지 않고 정규화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])

norm_scaled_x_data = (x_data - x_data.min()) / (x_data.max() - x_data.min())
norm_scaled_y_data = (y_data - y_data.min()) / (y_data.max() - y_data.min())
norm_scaled_y_data

array([0.        , 0.11111111, 0.7       , 0.83333333, 1.        ])

In [43]:
# 라이브러리를 사용하여 정규화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler() # 독립변수 x를 정규화 시킬 객체
norm_scaled_x_data = scaler_x.fit_transform(x_data)
scaler_y = MinMaxScaler() # 종속(타겟)변수 y를 정규화시킬 객체
norm_scaled_y_data = scaler_y.fit_transform(y_data)
norm_scaled_y_data

array([[0.        ],
       [0.11111111],
       [0.7       ],
       [0.83333333],
       [1.        ]])

In [46]:
# 라이브러리 쓰지 않고 표준화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
stan_scaled_x_data =(x_data - x_data.mean()) / x_data.std()
stan_scaled_y_data =(y_data - y_data.mean()) / y_data.std()
np.column_stack([x_data, norm_scaled_x_data, stan_scaled_x_data])

array([[ 1.        ,  0.        , -1.22474487],
       [ 2.        ,  0.11111111, -0.93313895],
       [ 5.        ,  0.44444444, -0.05832118],
       [ 8.        ,  0.77777778,  0.81649658],
       [10.        ,  1.        ,  1.39970842]])

In [47]:
np.column_stack([y_data, norm_scaled_y_data, stan_scaled_y_data])

array([[ 5.        ,  0.        , -1.32373476],
       [15.        ,  0.11111111, -1.04563922],
       [68.        ,  0.7       ,  0.42826713],
       [80.        ,  0.83333333,  0.76198177],
       [95.        ,  1.        ,  1.17912508]])

In [51]:
# 라이브러리를 사용하여 표준화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)

from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
stan_scaled_x_data = scaler_x.fit_transform(x_data)
scaler_y = StandardScaler()
stan_scaled_y_data = scaler_y.fit_transform(y_data)

In [52]:
# 스케일 조정된 데이터를 다시 복구
scaler_y.inverse_transform(stan_scaled_y_data)

array([[ 5.],
       [15.],
       [68.],
       [80.],
       [95.]])

In [57]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost (손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# Session & 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:norm_scaled_x_data,
                                                     y:norm_scaled_y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step, cost_val))

300/6000번째 cost:0.13600845634937286
600/6000번째 cost:0.04092090204358101
900/6000번째 cost:0.017457062378525734
1200/6000번째 cost:0.011667086742818356
1500/6000번째 cost:0.01023835875093937
1800/6000번째 cost:0.009885801002383232
2100/6000번째 cost:0.009798804298043251
2400/6000번째 cost:0.00977733638137579
2700/6000번째 cost:0.009772037155926228
3000/6000번째 cost:0.009770727716386318
3300/6000번째 cost:0.0097704092040658
3600/6000번째 cost:0.009770326316356659
3900/6000번째 cost:0.009770307689905167
4200/6000번째 cost:0.009770304895937443
4500/6000번째 cost:0.009770303033292294
4800/6000번째 cost:0.009770302101969719
5100/6000번째 cost:0.009770299308001995
5400/6000번째 cost:0.009770302101969719
5700/6000번째 cost:0.009770302101969719
6000/6000번째 cost:0.009770302101969719
